name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to GitHub Container Registry (GHCR)
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Pull Docker image from GHCR
      - name: Pull Docker image
        run: docker pull ghcr.io/fishmaniac/pharmacy-management-system/ubuntu-java:latest

      # Step 4: Build application inside Docker container
      - name: Build Pharmacy Management system
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            ghcr.io/fishmaniac/pharmacy-management-system/ubuntu-java:latest \
            /bin/bash -c "
              echo 'Starting Build Process...'
              java -version
              ls -althr
              ./build.sh  # Adjust this to your actual build script or commands
            "
      # TODO: Add tests here

      # Step 5: Deploy Jar file to releases
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.head_ref }}
          release_name: Release ${{ github.head_ref }}
          draft: false
          prerelease: false
      - name: Upload Jar to Release
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./PharmacyManagementSystem.jar
          asset_name: PharmacyManagementSystem.jar
          asset_content_type: application/jar
