name: Deploy Javadoc

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # if you have a protection rule on your repository, you'll need to give write permission to the workflow.
    steps:
      - name: Deploy JavaDoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 21
          javadoc-source-folder: docs
          target-folder: docs
          project: maven
          custom-command: javadoc -d docs -sourcepath . -subpackages PharmacyManagementSystem -windowtitle "Pharmacy Management System" -doctitle "Pharmacy Management System"
